version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          cd my-wp
          docker build -t cloudgenius/wp:${CIRCLE_SHA1}     .
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
          docker push cloudgenius/wp:${CIRCLE_SHA1}
          cd $HOME
          echo "${GKE_SERVICE_ACCOUNT}" | base64 --decode >> /tmp/gke_key.json
          gcloud auth activate-service-account --key-file /tmp/gke_key.json
          gcloud config set project ${GKE_PROJECT_ID}
          gcloud config set compute/zone ${GKE_COMPUTE_ZONE}
          gcloud --quiet container clusters get-credentials ${GKE_CLUSTER_NAME}
          kubectl get deploy
          kubectl set image deployment/wp wp=cloudgenius/wp:$(git log --format="%H" -n 1)
          kubectl annotate deployment.v1.apps/wp kubernetes.io/change-cause=$(git log --format="%H" -n 1)
          kubectl get deploy
