apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: nfs-server.default.svc.cluster.local
    path: "/wp"
---
apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wp
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
